### ISSUE TITLE
need a better code for interfaces for Java

### ISSUE THREAD

**Issue by SyntaxNova** [SyntaxNova/JAVA#1]

**Comment by AbhijeetP21** [comment]
// Define the interface
interface Animal {
    void eat();
    void sleep();
    void makeSound();
}

// Implement the Dog class
class Dog implements Animal {
    @Override
    public void eat() {
        System.out.println("Dog is eating.");
    }

    @Override
    public void sleep() {
        System.out.println("Dog is sleeping.");
    }

    @Override
    public void makeSound() {
        System.out.println("Dog barks: Woof Woof!");
    }
}

// Implement the Cat class
class Cat implements Animal {
    @Override
    public void eat() {
        System.out.println("Cat is eating.");
    }

    @Override
    public void sleep() {
        System.out.println("Cat is sleeping.");
    }

    @Override
    public void makeSound() {
        System.out.println("Cat meows: Meow Meow!");
    }
}

// Main class to demonstrate the usage
public class Main {
    public static void main(String[] args) {
        Animal myDog = new Dog();
        Animal myCat = new Cat();
        
        System.out.println("Dog:");
        myDog.eat();
        myDog.sleep();
        myDog.makeSound();
        
        System.out.println("\nCat:");
        myCat.eat();
        myCat.sleep();
        myCat.makeSound();
    }
}
